# Generated by Django 2.2.3 on 2019-07-11 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drp_query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
