# Generated by Django 2.2.3 on 2019-07-11 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drp_query', '0002_refugee_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
