# Generated by Django 2.2.3 on 2019-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='threat_rating',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
