# Generated by Django 2.2.3 on 2019-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_auto_20190715_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='threat_rating',
            field=models.IntegerField(),
        ),
    ]
