# Generated by Django 2.2.3 on 2019-07-15 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0003_auto_20190715_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugee',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
