# Generated by Django 2.2.3 on 2019-07-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_auto_20190715_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugee',
            name='necessities',
        ),
        migrations.RemoveField(
            model_name='refugee',
            name='threat_rating',
        ),
        migrations.AlterField(
            model_name='refugee',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
