# Generated by Django 2.2.3 on 2019-07-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0005_auto_20190716_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.CharField(default='thiruvalla', max_length=50),
        ),
    ]
